### PR TITLE
possible fix

### PR DESCRIPTION
**Pull request by clinton-hall**
Export Home Path for git clone

### CODE REVIEW

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/issues/1888

**Comment by phybersplice** [comment]
Merged ... and deployed.  Scripts are not to be found in the directory.
Only the original 2 .py scripts are present.
  
root@b2ec63e641d6:/app/nzbget/share/nzbget/scripts# ls
EMail.py  Logger.py

**Comment by phybersplice** [comment]
also 
root@b2ec63e641d6:/app/nzbget/share/nzbget/scripts# echo $HOME
/root

**Comment by phybersplice** [comment]
Logging into Docker and going to the console to manually pull your git, change the permissions to abc:abc result in this:

> root@b2ec63e641d6:/app/nzbget/share/nzbget/scripts/nzbToMedia/logs# cat nzbtomedia.log 
2022-09-27 20:32:11 WARNING ::MAIN:  category is set for CouchPotato and Watcher3. Please check your config in NZBGet
2022-09-27 20:32:11 INFO    ::MAIN: Python v3.9 will reach end of life in 1104 days.
2022-09-27 20:32:11 INFO    ::MAIN: Checking database structure...
2022-09-27 20:32:11 INFO    ::MAIN: Database upgrade required: Initial Schema
2022-09-27 20:32:11 INFO    ::MAIN: Checking if git needs an update
2022-09-27 20:32:11 ERROR   ::MAIN: Unable to determine installed version via git, please check your logs!
2022-09-27 20:32:11 INFO    ::MAIN: No update needed
2022-09-27 20:32:11 INFO    ::MAIN: nzbToMedia Version:12.1.10 Branch:master (Linux 4.4.180+)
2022-09-27 20:32:12 INFO    ::MAIN: #########################################################
2022-09-27 20:32:12 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2022-09-27 20:32:12 INFO    ::MAIN: #########################################################
2022-09-27 20:32:12 INFO    ::MAIN: Script triggered from NZBGet Version 21.1.
2022-09-27 20:32:12 INFO    ::MAIN: Auto-detected SECTION:Radarr
2022-09-27 20:32:12 INFO    ::MAIN: Calling Radarr:movies to post-process:Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
2022-09-27 20:32:12 INFO    ::MAIN: Attemping imdbID lookup for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
2022-09-27 20:32:12 INFO    ::MAIN: Searching folder and file names for imdbID ...
2022-09-27 20:32:12 INFO    ::MAIN: Searching IMDB for imdbID ...
2022-09-27 20:32:12 INFO    ::MAIN: Found imdbID [tt1745960]
2022-09-27 20:32:13 INFO    ::TRANSCODER: Checking [Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv] for corruption, please stand by ...
2022-09-27 20:32:13 INFO    ::TRANSCODER: SUCCESS: [Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv] has no corruption.
2022-09-27 20:32:13 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
2022-09-27 20:32:13 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-09-27 20:32:23 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-09-27 20:32:33 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-09-27 20:32:33 INFO    ::MAIN: The /app/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py script completed successfully.

However in nzbget messages, I see this:

> Tue Sep 27 20:32:07 2022	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: To add an exception for this directory, call:
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: To add an exception for this directory, call:
Tue Sep 27 20:32:07 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [WARNING]::MAIN:  category is set for CouchPotato and Watcher3. Please check your config in NZBGet
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: Python v3.9 will reach end of life in 1104 days.
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: Checking database structure...
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: Database upgrade required: Initial Schema
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: Checking if git needs an update
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: No update needed
Tue Sep 27 20:32:11 2022	INFO	nzbToMedia: [20:32:11] [INFO]::MAIN: nzbToMedia Version:12.1.10 Branch:master (Linux 4.4.180+)
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: #########################################################
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: #########################################################
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Script triggered from NZBGet Version 21.1.
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Auto-detected SECTION:Radarr
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Calling Radarr:movies to post-process:Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Attemping imdbID lookup for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Searching folder and file names for imdbID ...
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Searching IMDB for imdbID ...
Tue Sep 27 20:32:12 2022	INFO	nzbToMedia: [20:32:12] [INFO]::MAIN: Found imdbID [tt1745960]
Tue Sep 27 20:32:13 2022	INFO	nzbToMedia: [20:32:13] [INFO]::TRANSCODER: Checking [Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv] for corruption, please stand by ...
Tue Sep 27 20:32:13 2022	INFO	nzbToMedia: [20:32:13] [INFO]::TRANSCODER: SUCCESS: [Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv] has no corruption.
Tue Sep 27 20:32:13 2022	INFO	nzbToMedia: [20:32:13] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
Tue Sep 27 20:32:13 2022	INFO	nzbToMedia: [20:32:13] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
Tue Sep 27 20:32:23 2022	INFO	nzbToMedia: [20:32:23] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: [20:32:33] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: [20:32:33] [INFO]::MAIN: The /app/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py script completed successfully.
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: Changing to directory: /app/nzbget/share/nzbget/scripts/nzbToMedia
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: -- Cleaning bytecode --
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: REASON : Error Code: 128
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: REASON : Error Code: 128
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: Returning to directory:  /run/s6/legacy-services/nzbget
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: -- Cleanup finished --
Tue Sep 27 20:32:33 2022	INFO	nzbToMedia: Radarr: Successfully post-processed Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX!
Tue Sep 27 20:32:33 2022	INFO	Post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX successful
Tue Sep 27 20:32:33 2022	INFO	Collection Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX added to history

**Comment by clinton-hall** [comment]
does your NAS accept Sudo command?
The issue appears to be similar to this
https://github.com/just-containers/s6-overlay/issues/207
I'll need to try and set up a docker here to see if I can reproduce and find the right combination to clone as user so that future pull requests work.

**Comment by phybersplice** [comment]
It does via the native CLI. However everything is run from the docker container and I'm already root there. 

It's a Synology 1821+

**Comment by clinton-hall** [comment]
honestly, it may just be easier to reset it all and do the occasional git pull manually.
To be honest, it isn't like my project is getting updated all that often these days, and if I understand the docker setup correctly, you are likely to be updating the container on a semi-regular basis anyway?
You can disable the auto-update via nzbget webUI for nzbToMedia 
`auto_update=0`
also in autoProcessMedia.cfg
```
[General]
    auto_update = 0
    version_notify = 0
```
disabling the version notify should stop all attempts at using git, so this should stop the errors in the logs.

In theory, it would be possible to modify the container so that it does (as root) a git pull every time the container restarts.... this might be a good compromise.

in /docker-nzbget/root/etc/services.d/nzbget)/run
```
#git clone if not exisiting
[ -d /app/nzbget/share/nzbget/scripts/nzbToMedia/.git ] || exec git clone https://github.com/clinton-hall/nzbToMedia.git /app/nzbget/share/nzbget/scripts/nzbToMedia
#git pull on each start
cd /app/nzbget/share/nzbget/scripts/nzbToMedia
exec git pull
#end

```

**Comment by phybersplice** [comment]
I tried adding the data like suggested to the services.d/nzbget/run file.

> #!/usr/bin/with-contenv bash
> 
> # parse env vars to options
> OPTIONS=""
> if [[ ${NZBGET_USER} && ${NZBGET_USER-x} ]]; then
>   OPTIONS+="-o ControlUsername=${NZBGET_USER} "
> fi
> if [[ ${NZBGET_PASS} && ${NZBGET_PASS-x} ]]; then
>   OPTIONS+="-o ControlPassword=${NZBGET_PASS} "
> fi
> #git clone if not exisiting
> [ -d /app/nzbget/share/nzbget/scripts/nzbToMedia/.git ] || exec git clone https://github.com/clinton-hall/nzbToMedia.git /app/nzbget/share/nzbget/scripts/nzbToMedia
> #git pull on each start
> cd /app/nzbget/share/nzbget/scripts/nzbToMedia
> exec git pull
> #end
> exec \
>     s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf \
>     -o OutputMode=log ${OPTIONS}

nzbget does not startup.

**Review by phybersplice — COMMENTED** [review]
typo

**Comment by clinton-hall** [comment]
what happens if you remove both instances of `exec`

```
#git clone if not exisiting
[ -d /app/nzbget/share/nzbget/scripts/nzbToMedia/.git ] || git clone https://github.com/clinton-hall/nzbToMedia.git /app/nzbget/share/nzbget/scripts/nzbToMedia
#git pull on each start
cd /app/nzbget/share/nzbget/scripts/nzbToMedia
git pull
#end
exec
s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf
-o OutputMode=log ${OPTIONS}
```

**Comment by phybersplice** [comment]
While this pulls the git and does a root:root ownership, it also has a slew of errors when post processing:

> Wed Sep 28 22:54:04 2022	INFO	Post-processing again Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:04 2022	INFO	Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX returned from history back to download queue
> Wed Sep 28 22:54:04 2022	INFO	Queueing Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX for post-processing
> Wed Sep 28 22:54:04 2022	INFO	Cleaning up Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:04 2022	INFO	Nothing to cleanup for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:04 2022	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: To add an exception for this directory, call:
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: To add an exception for this directory, call:
> Wed Sep 28 22:54:05 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: -- Cleaning bytecode --
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: REASON : Error Code: 128
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: REASON : Error Code: 128
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: -- Cleanup finished --
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: Traceback (most recent call last):
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 735, in <module>
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     import core
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     from core import logger, main_db, version_check, databases, transcoder
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/databases.py", line 11, in <module>
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     from core.utils import backup_versioned_file
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/utils/__init__.py", line 14, in <module>
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     from core.utils.download_info import get_download_info, update_download_info_status
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/utils/download_info.py", line 14, in <module>
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     database = main_db.DBConnection()
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/main_db.py", line 65, in __init__
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia:     self.connection = sqlite3.connect(db_filename(filename), 20)
> Wed Sep 28 22:54:06 2022	INFO	nzbToMedia: sqlite3.OperationalError: unable to open database file
> Wed Sep 28 22:54:06 2022	ERROR	Post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX failed (terminated with unknown status)
> Wed Sep 28 22:54:06 2022	INFO	Collection Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX added to history
> Wed Sep 28 22:54:34 2022	INFO	Reloading...
> Wed Sep 28 22:54:35 2022	INFO	nzbget 21.1 server-mode
> Wed Sep 28 22:54:35 2022	DETAIL	Downloading omgwtfnzbs
> Wed Sep 28 22:54:35 2022	DETAIL	Downloading nzbgeek.info
> Wed Sep 28 22:54:35 2022	DETAIL	Download nzbgeek.info completed
> Wed Sep 28 22:54:35 2022	DETAIL	Scheduling update for feed nzbgeek.info in 15 minute(s)
> Wed Sep 28 22:54:35 2022	DETAIL	nzbgeek.info has no new items
> Wed Sep 28 22:54:35 2022	DETAIL	Download omgwtfnzbs completed
> Wed Sep 28 22:54:35 2022	DETAIL	Scheduling update for feed omgwtfnzbs in 15 minute(s)
> Wed Sep 28 22:54:35 2022	DETAIL	omgwtfnzbs has no new items
> Wed Sep 28 22:54:40 2022	INFO	Post-processing again Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:40 2022	INFO	Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX returned from history back to download queue
> Wed Sep 28 22:54:40 2022	INFO	Queueing Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX for post-processing
> Wed Sep 28 22:54:41 2022	INFO	Cleaning up Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:41 2022	INFO	Nothing to cleanup for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:41 2022	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: To add an exception for this directory, call:
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: fatal: detected dubious ownership in repository at '/app/nzbget/share/nzbget/scripts/nzbToMedia'
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: To add an exception for this directory, call:
> Wed Sep 28 22:54:41 2022	INFO	nzbToMedia: 	git config --global --add safe.directory /app/nzbget/share/nzbget/scripts/nzbToMedia
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: -- Cleaning bytecode --
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: REASON : Error Code: 128
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: REASON : Error Code: 128
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: -- Cleanup finished --
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: Traceback (most recent call last):
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 735, in <module>
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     import core
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     from core import logger, main_db, version_check, databases, transcoder
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/databases.py", line 11, in <module>
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     from core.utils import backup_versioned_file
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/utils/__init__.py", line 14, in <module>
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     from core.utils.download_info import get_download_info, update_download_info_status
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/utils/download_info.py", line 14, in <module>
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     database = main_db.DBConnection()
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:   File "/app/nzbget/share/nzbget/scripts/nzbToMedia/core/main_db.py", line 65, in __init__
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia:     self.connection = sqlite3.connect(db_filename(filename), 20)
> Wed Sep 28 22:54:43 2022	INFO	nzbToMedia: sqlite3.OperationalError: unable to open database file
> Wed Sep 28 22:54:43 2022	ERROR	Post-process-script nzbToMedia/nzbToMedia.py for Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX failed (terminated with unknown status)
> Wed Sep 28 22:54:43 2022	INFO	Collection Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX added to history

**Comment by phybersplice** [comment]
Changing permissions manually when logged into the nzbget console within docker, and using a chown -R abc:abc nzbToMedia/ cleans up the errors, but I'm still left with the error:

> nzbToMedia: warning: unable to access '/root/.config/git/ignore': Permission denied

Also tried to disable the auto checking for updates by adjusting the GUI option - doesn't make a difference.
I edited the autoprocessmedia.cfg file and after editing, and post processing again, there's an even worse list of errors.  I delete the file and let the system recreate the file and it postprocesses with the Permission Denied error above.
Curious isn't it?

**Comment by clinton-hall** [comment]
ok. So when you edited autoProcessMedia.cfg, you did so as root, so then the script gives errors about setting config?

After you change version_notify = 0 you will need to change autoProcessMedia.cfg to abc ownership again.

If that works, then we can probable set the permissions automatically.

```
#git clone if not exisiting
[ -d /app/nzbget/share/nzbget/scripts/nzbToMedia/.git ] || git clone https://github.com/clinton-hall/nzbToMedia.git /app/nzbget/share/nzbget/scripts/nzbToMedia
#git pull on each start
cd /app/nzbget/share/nzbget/scripts/nzbToMedia
git pull
chown -R abc:abc /app/nzbget/share/nzbget/scripts/nzbToMedia
#end
exec
s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf
-o OutputMode=log ${OPTIONS}
```

So if that is all working, what I need to do is change the version notify to be editable from NZBGet gui.

**Comment by phybersplice** [comment]
When I did the edit, I was root yes, but the file is still owned by abc:abc.

-rw-r--r-- 1 abc abc 25851 Sep 29 20:29 autoProcessMedia.cfg.old
-rw-r--r-- 1 abc abc 16384 Sep 29 20:30 nzbtomedia.db
-rw-r--r-- 1 abc abc 27494 Sep 29 20:30 autoProcessMedia.cfg

As soon as I do an edit, the ownership doesn't change and it seems to not play nice with the scripts throwing errors all over the place.

**Pull request merged**
